### ISSUE TITLE
Image not showing in documentation

### ISSUE THREAD

**Issue by uo67609** [Arquisoft/viade_es3b#20]
Composite structure diagram.jpg reference was fixed in 05_building_block_view.adoc to conform the standard of image paths in the other documents, but it is not showing now.

**Comment by IsmaCadenas** [comment]
I try to change the doc to solve the error but i cannot view the image correctly

**Comment by JorgeIturrioz** [comment]
This was solved here: 890ed22d22777cef8199493b1084e8bcae7eb098

Remember closing issues whenever they're already finished
