### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by AlfonsoLozana** [Arquisoft/viade_es3b#22]
I have made a logo, for the application although it is quite simple it can serve. I hope to improve it in the future, to make it look more professional.
![Captura de pantalla de 2020-03-07 12-05-41](https://user-images.githubusercontent.com/57018030/76168689-46c98780-6172-11ea-9e4f-8ad34178d3eb.png)

**Comment by IsmaCadenas** [comment]
The logo is finished
