### ISSUE TITLE
Revisión prototipo

### ISSUE THREAD

**Issue by cidinene** [Arquisoft/viade_es3b#24]
La gestión de ramas es correcto, habéis contribuido todos, ya es un exito entenderse.

Por otro lado, habéis conseguido autentificaros, ya estáis trabajando con el pod y guardáis todavía sin parsear.

Habéis integrado un servicio de mapas aunque no está gestionando la ruta que se carga del Pod Server.

Los test no funcionan, es un requisito importante para el proyecto tener test unitarios y una cobertura de código.

Vais bastante bien, pero recordar que hay que incluir los test, parsear las rutas y guardarlas siguiendo el esquema de referencia, y luego trabajar con los mapas.Aún queda trabajo, pero vais bien .

Un saludo.

@cidinene

**Comment by uo67609** [comment]
Yo aún no he conseguido loguearme en la aplicación. Seguramente debería ser capaz de modificar el código que está ya hecho para arreglar el problema, pero el caso es que no lo soy, y no puedo entrar en la aplicación para hacer las pruebas de aceptación, menos aún probarla para asegurarme de que todo está correcto y poder envolverla en un contenedor docker para dejarla lista para las pruebas de carga.

**Comment by cidinene** [comment]
Puedes explicar " no consigo loguearme  en la aplicación" . ¿Con qué cuenta? ¿Que fallo te da?
 ¿Usando cucumber? ¿Has probado los ejemplos indicados en el powerPoint de docker?
Saludos

**Comment by uo67609** [comment]
El problema principal es que no me he involucrado suficiente en el desarrollo del código por falta de base técnica, y ahora que la versión de github no funciona, sólo algunos compañeros de equipo tienen la aplicación con funcionalidad en su máquina local, por lo que yo, que no consigo disponer de esa funcionalidad, no puedo acceder a los formularios para tratar de hacer pruebas de aceptación (entiendo que necesito hacer entrada/salida) en las pantallas del proyecto.
De nuevo, como no puedo ejecutarla completa, no se si la versión que empaquetaría dentro de un contenedor docker estaría funcionando, así que, aunque fuera capaz de llevar a cabo esas dos tareas, ahora mismo no puedo aportar nada en ellas por no tener acceso, ni siquiera capacidad de logueareme, a la aplicación.
________________________________

**Comment by uo67609** [comment]
Vaya, he explicado el problema pero no he contestado a tu pregunta.
La aplicación requiere un webid o unas credenciales solid para entrar y poder usar su funcionalidad, una vez identificado.
He probado con varios usuarios de solid community con el mismo éxito, ninguno.
________________________________

**Comment by cidinene** [comment]
¿Pero te has creado una cuenta?   ¿ Con qué rama estás trabajando? ¿ la que les funciona a tus compañeros es la rama develop? 
¿Has probado los ejemplos indicados en el powerPoint de docker?

**Comment by uo67609** [comment]
Sí, varias cuentas. Empecé con una cuenta en solid community con mi uo de la universidad, pero haciendo pruebas, dejé de tener acceso a  la misma (un día en la sala de libre acceso en el que iba muy lento) porque, creo, que quité los checkboxes de permisos a todas las aplicaciones con acceso al pod, incluido el login. Una vez perdida esa cuenta, cree otra, llamada "dummypod", con la que traté de hacer pruebas una temporada en la que intentaba persistir información en mi pod desde el esqueleto que nos suministrasteis. Eso fue en una fase temprana del desarrollo, más adelante algunos de mis compañeros de equipo fueron consiguiendo avances, como los que viste en la presentación del prototipo, como mostrar el mapa con rutas que se encontraban almacenadas en la misma carpeta que el código fuente del proyecto, aunque eso ya ha quedado obsoleto, porque actualmente el proyecto almacena y carga rutas desde un pod de solid.
De todos modos, la funcionalidad que te describo la he visto remotamente y me la han descrito mis compañeros, porque, como te decía en los otros correos, yo aún no he conseguido usar la aplicación.
Cuando se implementó la funcionalidad inicial del mapa, se creó una rama específica en la que estaba el proyecto con dicha funcionalidad, pero más adelante se fueron haciendo merges e incorporando las características a la rama máster. Actualmente, si no me equivoco, la rama máster tiene todas las características desarrolladas incorporadas, aunque hay problemas que hacen que no se pueda usar la aplicación desde git hub. Esta misma tarde me dieron una versión del proyecto con la que intenté hacer nuevas pruebas, pero en mi maquina local tampoco puedo entrar en ella, con lo que sigo atascado sin poder aportar al proyecto en áreas en las que mis conocimientos sí podrían ser de utilidad, como haciendo pruebas de aceptación o haciendo las veces de devops y tratando de crear un contenedor docker con la aplicación para que realicéis, cuando sea oportuno, las pruebas de carga.
________________________________
