### ISSUE TITLE
Revisión prototipo 2

### ISSUE THREAD

**Issue by cidinene** [Arquisoft/viade_es3b#28]
Como comentado en la videoconferencia mantenida con vosotros, he tenido problemas con algun fichero geoJson , pero en general , por la prueba realizada con vosotros, veo  que  permite crear rutas , compartir y ver las rutas de los amigos Comprobad que la aplicación no falla si tiene un problema al leer alguna ruta no correcta ,tanto del fichero subido como del pod del usuario,  También sería necesario que no obliguéis a que las imágenes sean png. A continuación os presento un listado de cosas que se pueden mejorar si tenéis tiempo:
Mejorar la parte de compartir , que una vez creadas se pueda compartir aunque no se haya especificado antes.  
Funcionalidades adicionales : editar rutas , subir con otros formatos

Felicitaros por haber conseguido trabajar en equipo, aunque el trabajo ha sido muy desigualdad entre vosotros. No veo actividad de Federico, aunque haya asistido a clase. También tengo en cuenta que contabais con uno menos, ya que Joaquín Ceballos no ha participado en la asignatura.  La documentación ha sido actualizada y rectificado lo indicado en la primera revisión , hay pruebas unitarias y  de aceptación. En la documentación los apartados 8 y 9 no parecen finalizados. Revisarlos y Felicidades.

Un saludo

**Comment by uo67609** [comment]
Hola Irene, no tengo apenas commits porque lo que he estado realizando es tratar de desplegar la aplicación en local para poder hacer pruebas de carga y usarla sin necesidad de acceder a la página de github, de modo que fuera alojable en el servidor de la elección del usuario. Hasta ahora lo que he conseguido es desplegar la release de producción generada por el proyecto en un servidor de aplicaciones Nginx en mi máquina, pero sigo sin ser capaz de configurarlo para que se pueda acceder a la aplicación desde una máquina que no sea la misma en la que está alojada el servidor, a pesar de que el despliegue en github sí consigue realizarlo.
He visto que la url arquisoft.github.io está hardcodeada en varios ficheros de nuestro proyecto, y he probado a reemplazarla por la dirección ip del servidor en el que intento alojarla, sin resultado, de modo que me estoy quedando sin ideas para tratar de hacer la apliación portable.
Con estas limitaciones, los esfuerzos que he hecho para crear un contendor docker con la aplicación se quedan en nada, dado que no es útil crear el contenedor (tengo varios, basados en apache, nginx y otro con un nginx creado sobre un contenedor ubuntu para instalar al nginx los módulos necesarios para servir código nodejs correctamente) para después no poder acceder a la aplicación dado que el contenedor es una máquina diferente a la que se accede con el navegador, por lo que la aplicación no funciona. Una opción descabellada sería crear un contenedor con GUI para poder hacer pruebas de carga y "distribuir" la aplicación, pero no veo cómo alguien podría querer un contenedor que requiera 6 GB de RAM para poder ejecutar nuestra aplicación, y tener el servidor instalado en su propia máquina para poder usarla.
